# Generated by Django 5.2.5 on 2025-08-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('customer_photo', models.ImageField(blank=True, null=True, upload_to='reviews/')),
            ],
        ),
    ]
