# Generated by Django 5.2.5 on 2025-09-02 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientApp', '0004_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='title',
        ),
    ]
