from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('contact-us/', views.contact, name="contact"),
    path('make-my-booking/', views.book_appointment, name="booking"),
    path('admin-page/', views.adminviewpage, name="admin"),
    path('Appointment_booking_list/', views.booking_list, name="Appointment_booking_list"),
    path('make-my-booking/', views.book_appointment, name="booking"),
    path('our-services/', views.ourServices, name="our_services"),
    path("about-us/", views.about, name="about"),
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path("order/", views.cone_order, name="order"),
    path("place-order/", views.place_order, name="place_order"),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.profile_view, name='edit_profile'),
    path('dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('orders/', views.order_list, name='order_list'),
    path('orders/<int:order_id>/', views.order_detail, name='order_detail'),
    path('appointments/', views.appointment_booking_list, name='Appointment_booking_list'),
    path('appointments/delete/<int:booking_id>/', views.delete_booking, name='delete_booking'),
    path('manage-gallery/', views.manage_gallery, name='manage_gallery'),
    path('our-product/', views.our_product, name='our_product'),
    path('manage-product/', views.manage_product, name='manage_product'),
    path('manage-user/', views.manage_user, name='manage_user'),
    path('cart/', views.cart_view, name='cart'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('our-product/', views.product_list, name='product_list'),
    path('manage-products/', views.manage_products, name='manage_products'),
    path('manage-products/add/', views.add_product, name='add_product'),
    path('manage-products/edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('manage-products/delete/<int:product_id>/', views.delete_product, name='delete_product'),
]